"""Generated by ordeal explorer -- replayable high-coverage paths."""

from tests.test_chaos_budget import BudgetControllerChaos
from tests.test_chaos_circuit_breaker import CircuitBreakerChaos
from tests.test_chaos_concurrency import ConcurrencyLimiterChaos
from tests.test_chaos_engine import EngineChaos
from tests.test_chaos_engine import ProviderFallbackChaos
from tests.test_chaos_metrics import MetricsCollectorChaos
from tests.test_chaos_rlm import BudgetTrackerChaos
from tests.test_chaos_rlm import CrossModuleChaos
from tests.test_chaos_rlm import TokenBudgetPoolChaos
from tests.test_chaos_session import SessionStateChaos


def test_explore_tokenbudgetpoolchaos_1():
    """TokenBudgetPoolChaos: 41 steps, 53 edges"""
    machine = TokenBudgetPoolChaos()
    try:
        for f in machine._faults:
            if f.name == "jitter(enzu.rlm.budget.TokenBudgetPool.reserve, 0.001)":
                f.activate()
        for f in machine._faults:
            if f.name == "jitter(enzu.rlm.budget.TokenBudgetPool.reserve, 0.001)":
                f.deactivate()
        machine.do_reserve(prompt_tokens=0, requested_output=101)
        for f in machine._faults:
            if f.name == "jitter(enzu.rlm.budget.TokenBudgetPool.reserve, 0.001)":
                f.activate()
        for f in machine._faults:
            if f.name == "jitter(enzu.rlm.budget.TokenBudgetPool.reserve, 0.001)":
                f.deactivate()
        for f in machine._faults:
            if f.name == "jitter(enzu.rlm.budget.TokenBudgetPool.reserve, 0.001)":
                f.activate()
        machine.do_reserve(prompt_tokens=80, requested_output=1)
        machine.do_release()
        machine.check_snapshot()
        machine.concurrent_reserve_commit()
        machine.do_commit(actual=None)
        for f in machine._faults:
            if f.name == "jitter(enzu.rlm.budget.TokenBudgetPool.reserve, 0.001)":
                f.deactivate()
        machine.do_commit(actual=10)
        for f in machine._faults:
            if f.name == "jitter(enzu.rlm.budget.TokenBudgetPool.reserve, 0.001)":
                f.activate()
        for f in machine._faults:
            if f.name == "jitter(enzu.rlm.budget.TokenBudgetPool.reserve, 0.001)":
                f.deactivate()
        machine.check_snapshot()
        machine.do_reserve(prompt_tokens=None, requested_output=153)
        for f in machine._faults:
            if f.name == "jitter(enzu.rlm.budget.TokenBudgetPool.reserve, 0.001)":
                f.activate()
        for f in machine._faults:
            if f.name == "jitter(enzu.rlm.budget.TokenBudgetPool.reserve, 0.001)":
                f.deactivate()
        machine.do_reserve(prompt_tokens=87, requested_output=21)
        machine.do_commit(actual=148)
        machine.check_snapshot()
        for f in machine._faults:
            if f.name == "jitter(enzu.rlm.budget.TokenBudgetPool.reserve, 0.001)":
                f.activate()
        machine.check_snapshot()
        machine.check_snapshot()
        machine.do_release()
        machine.do_commit(actual=192)
        for f in machine._faults:
            if f.name == "jitter(enzu.rlm.budget.TokenBudgetPool.reserve, 0.001)":
                f.deactivate()
        for f in machine._faults:
            if f.name == "jitter(enzu.rlm.budget.TokenBudgetPool.reserve, 0.001)":
                f.activate()
        machine.check_snapshot()
        machine.concurrent_reserve_commit()
        machine.concurrent_reserve_commit()
        for f in machine._faults:
            if f.name == "jitter(enzu.rlm.budget.TokenBudgetPool.reserve, 0.001)":
                f.deactivate()
        for f in machine._faults:
            if f.name == "jitter(enzu.rlm.budget.TokenBudgetPool.reserve, 0.001)":
                f.activate()
        machine.check_snapshot()
        for f in machine._faults:
            if f.name == "jitter(enzu.rlm.budget.TokenBudgetPool.reserve, 0.001)":
                f.deactivate()
        machine.do_release()
        for f in machine._faults:
            if f.name == "jitter(enzu.rlm.budget.TokenBudgetPool.reserve, 0.001)":
                f.activate()
        machine.do_reserve(prompt_tokens=73, requested_output=123)
        machine.do_commit(actual=88)
        for f in machine._faults:
            if f.name == "jitter(enzu.rlm.budget.TokenBudgetPool.reserve, 0.001)":
                f.deactivate()
    finally:
        machine.teardown()


def test_explore_budgettrackerchaos_2():
    """BudgetTrackerChaos: 41 steps, 38 edges"""
    machine = BudgetTrackerChaos()
    try:
        machine.check_percentage()
        machine.check_percentage()
        machine.consume_usage(cost=0.8175709147946582, output=0, total=9)
        machine.check_remaining()
        machine.check_percentage()
        machine.check_percentage()
        machine.check_percentage()
        machine.consume_usage(cost=0.48192696677142577, output=79, total=15)
        machine.check_percentage()
        machine.consume_usage(cost=0.38441414331942425, output=50, total=30)
        machine.consume_usage(cost=0.3786702713516873, output=47, total=200)
        machine.consume_usage(cost=0.1411145362774298, output=32, total=60)
        machine.check_percentage()
        machine.consume_usage(cost=0.18253878691117323, output=85, total=27)
        machine.check_remaining()
        machine.check_percentage()
        machine.check_percentage()
        machine.check_percentage()
        machine.check_percentage()
        machine.check_percentage()
        machine.consume_usage(cost=0.682662853580673, output=65, total=57)
        machine.consume_usage(cost=1.4884797287369102e-60, output=29, total=116)
        machine.check_percentage()
        machine.consume_usage(cost=0.0, output=97, total=0)
        machine.check_percentage()
        machine.consume_usage(cost=0.7714365559355056, output=86, total=133)
        machine.consume_usage(cost=2.225073858507203e-309, output=26, total=122)
        machine.consume_usage(cost=0.9359986971427323, output=0, total=0)
        machine.consume_usage(cost=0.023802277015640312, output=90, total=131)
        machine.check_remaining()
        machine.check_percentage()
        machine.check_remaining()
        machine.consume_usage(cost=9.105757386698987e-10, output=87, total=103)
        machine.check_remaining()
        machine.check_percentage()
        machine.check_percentage()
        machine.consume_usage(cost=0.9169635998831998, output=49, total=53)
        machine.check_remaining()
        machine.check_remaining()
        machine.check_remaining()
        machine.check_percentage()
    finally:
        machine.teardown()


def test_explore_crossmodulechaos_3():
    """CrossModuleChaos: 41 steps, 132 edges"""
    machine = CrossModuleChaos()
    try:
        machine.concurrent_requests()
        machine.concurrent_requests()
        machine.execute_request(
            cost=0.2933287964526965, input_tokens=8, output_tokens=5
        )
        machine.concurrent_requests()
        machine.concurrent_requests()
        machine.concurrent_requests()
        machine.concurrent_requests()
        machine.concurrent_requests()
        machine.execute_request(
            cost=0.4406078538942678, input_tokens=36, output_tokens=30
        )
        machine.concurrent_requests()
        machine.concurrent_requests()
        machine.concurrent_requests()
        machine.concurrent_requests()
        machine.concurrent_requests()
        machine.concurrent_requests()
        machine.concurrent_requests()
        machine.execute_request(
            cost=0.3649679812150815, input_tokens=3, output_tokens=1
        )
        machine.concurrent_requests()
        machine.execute_request(
            cost=0.3333333333333333, input_tokens=33, output_tokens=38
        )
        machine.execute_request(
            cost=0.010000000000000002, input_tokens=39, output_tokens=16
        )
        machine.concurrent_requests()
        machine.concurrent_requests()
        machine.execute_request(cost=0.5, input_tokens=24, output_tokens=47)
        machine.execute_request(
            cost=0.4538851611685315, input_tokens=6, output_tokens=46
        )
        machine.execute_request(
            cost=0.3947531848887579, input_tokens=13, output_tokens=36
        )
        machine.concurrent_requests()
        machine.concurrent_requests()
        machine.execute_request(cost=0.01, input_tokens=41, output_tokens=40)
        machine.concurrent_requests()
        machine.concurrent_requests()
        machine.execute_request(
            cost=0.09157239707389282, input_tokens=44, output_tokens=1
        )
        machine.concurrent_requests()
        machine.execute_request(cost=0.01, input_tokens=19, output_tokens=13)
        machine.execute_request(
            cost=0.20849827575452173, input_tokens=10, output_tokens=41
        )
        machine.execute_request(
            cost=0.49999999999999994, input_tokens=9, output_tokens=29
        )
        machine.concurrent_requests()
        machine.execute_request(
            cost=0.04319417760636518, input_tokens=14, output_tokens=7
        )
        machine.concurrent_requests()
        machine.execute_request(
            cost=0.01725206621048861, input_tokens=1, output_tokens=44
        )
        machine.concurrent_requests()
        machine.execute_request(
            cost=0.08819583570538912, input_tokens=39, output_tokens=10
        )
    finally:
        machine.teardown()


def test_explore_budgetcontrollerchaos_4():
    """BudgetControllerChaos: 41 steps, 102 edges"""
    machine = BudgetControllerChaos()
    try:
        for f in machine._faults:
            if f.name == "jitter(enzu.budget.count_tokens, 5.0)":
                f.activate()
        for f in machine._faults:
            if f.name == "jitter(enzu.budget.count_tokens, 5.0)":
                f.deactivate()
        machine.do_serialize()
        machine.do_serialize()
        for f in machine._faults:
            if f.name == "jitter(enzu.budget.count_tokens, 5.0)":
                f.activate()
        for f in machine._faults:
            if f.name == "jitter(enzu.budget.count_tokens, 5.0)":
                f.deactivate()
        for f in machine._faults:
            if f.name == "jitter(enzu.budget.count_tokens, 5.0)":
                f.activate()
        machine.do_serialize()
        machine.do_serialize()
        machine.do_record_usage(
            cost=1.3574223008285695, input_tokens=62, output_tokens=53
        )
        machine.do_pre_call_check(input_tokens=166, max_output=48)
        machine.do_pre_call_check(input_tokens=0, max_output=221)
        machine.do_record_usage(
            cost=0.9705916939048047, input_tokens=29, output_tokens=79
        )
        for f in machine._faults:
            if f.name == "jitter(enzu.budget.count_tokens, 5.0)":
                f.deactivate()
        machine.do_record_usage(
            cost=0.5802564041362303, input_tokens=84, output_tokens=11
        )
        for f in machine._faults:
            if f.name == "jitter(enzu.budget.count_tokens, 5.0)":
                f.activate()
        for f in machine._faults:
            if f.name == "jitter(enzu.budget.count_tokens, 5.0)":
                f.deactivate()
        machine.do_pre_call_check(input_tokens=23, max_output=229)
        machine.do_serialize()
        for f in machine._faults:
            if f.name == "jitter(enzu.budget.count_tokens, 5.0)":
                f.activate()
        for f in machine._faults:
            if f.name == "jitter(enzu.budget.count_tokens, 5.0)":
                f.deactivate()
        machine.do_serialize()
        machine.do_record_usage(cost=2.2250738585e-313, input_tokens=0, output_tokens=8)
        machine.do_serialize()
        for f in machine._faults:
            if f.name == "jitter(enzu.budget.count_tokens, 5.0)":
                f.activate()
        machine.do_pre_call_check(input_tokens=174, max_output=97)
        machine.do_pre_call_check(input_tokens=76, max_output=0)
        machine.do_record_usage(cost=0.0, input_tokens=45, output_tokens=48)
        machine.do_record_usage(cost=0.3, input_tokens=75, output_tokens=28)
        for f in machine._faults:
            if f.name == "jitter(enzu.budget.count_tokens, 5.0)":
                f.deactivate()
        for f in machine._faults:
            if f.name == "jitter(enzu.budget.count_tokens, 5.0)":
                f.activate()
        machine.do_serialize()
        machine.do_serialize()
        machine.do_serialize()
        machine.do_pre_call_check(input_tokens=154, max_output=84)
        machine.do_record_usage(
            cost=1.0885208881765754e-70, input_tokens=27, output_tokens=61
        )
        machine.do_serialize()
        machine.do_pre_call_check(input_tokens=144, max_output=254)
        machine.do_pre_call_check(input_tokens=93, max_output=60)
        for f in machine._faults:
            if f.name == "jitter(enzu.budget.count_tokens, 5.0)":
                f.deactivate()
        machine.do_record_usage(
            cost=1.0794653234225658e-101, input_tokens=57, output_tokens=3
        )
    finally:
        machine.teardown()


def test_explore_enginechaos_5():
    """EngineChaos: 41 steps, 251 edges"""
    machine = EngineChaos()
    try:
        for f in machine._faults:
            if (
                f.name
                == "intermittent_http_error(tests.test_chaos_engine._chaos_provider_generate, every 3, 503)"
            ):
                f.activate()
        for f in machine._faults:
            if (
                f.name
                == "intermittent_http_error(tests.test_chaos_engine._chaos_provider_generate, every 3, 503)"
            ):
                f.deactivate()
        machine.run_with_verification(
            output_text="\x86Ä?\x9e", substrings=["\U000d5f60É𦉊"]
        )
        machine.run_with_verification(
            output_text="虸\x12\U000c80e7È¾\U000a6052°\U0004e2b7ÅeÅ",
            substrings=["\U00074b12\U0004794e", "no_output"],
        )
        for f in machine._faults:
            if (
                f.name
                == "intermittent_http_error(tests.test_chaos_engine._chaos_provider_generate, every 3, 503)"
            ):
                f.activate()
        for f in machine._faults:
            if (
                f.name
                == "intermittent_http_error(tests.test_chaos_engine._chaos_provider_generate, every 3, 503)"
            ):
                f.deactivate()
        for f in machine._faults:
            if (
                f.name
                == "intermittent_http_error(tests.test_chaos_engine._chaos_provider_generate, every 3, 503)"
            ):
                f.activate()
        machine.run_with_verification(output_text="", substrings=["0"])
        machine.run_with_verification(
            output_text="OPENROUTER_REFERER", substrings=["=", "\U00096e659O"]
        )
        machine.run_with_fallback(output_text="\x08§")
        machine.run_task(
            max_tokens=200, max_total_tokens=None, output_text="㰣", provider_fails=True
        )
        machine.run_task(
            max_tokens=723,
            max_total_tokens=10,
            output_text="\U000c22e9¬ó\x08$𪌄I\x0e",
            provider_fails=False,
        )
        machine.run_with_fallback(output_text="\x86")
        for f in machine._faults:
            if (
                f.name
                == "intermittent_http_error(tests.test_chaos_engine._chaos_provider_generate, every 3, 503)"
            ):
                f.deactivate()
        machine.run_with_fallback(output_text="¦")
        for f in machine._faults:
            if (
                f.name
                == "intermittent_http_error(tests.test_chaos_engine._chaos_provider_generate, every 3, 503)"
            ):
                f.activate()
        for f in machine._faults:
            if (
                f.name
                == "intermittent_http_error(tests.test_chaos_engine._chaos_provider_generate, every 3, 503)"
            ):
                f.deactivate()
        machine.run_task(
            max_tokens=163,
            max_total_tokens=2192,
            output_text="\U000fc9c7\x88",
            provider_fails=True,
        )
        machine.run_with_verification(
            output_text="¦Âi",
            substrings=["Ý}", "\x03ý", "\U000a89ae\x88\U0009b71f[X©¨CòT"],
        )
        for f in machine._faults:
            if (
                f.name
                == "intermittent_http_error(tests.test_chaos_engine._chaos_provider_generate, every 3, 503)"
            ):
                f.activate()
        for f in machine._faults:
            if (
                f.name
                == "intermittent_http_error(tests.test_chaos_engine._chaos_provider_generate, every 3, 503)"
            ):
                f.deactivate()
        machine.run_with_verification(
            output_text="Ìú\x82",
            substrings=["\x19«𦱌", "\t þì\U000c5abc\x8b\U00107b66Ø"],
        )
        machine.run_with_fallback(output_text="0")
        machine.run_with_verification(output_text="\x7f", substrings=["2\x8b"])
        for f in machine._faults:
            if (
                f.name
                == "intermittent_http_error(tests.test_chaos_engine._chaos_provider_generate, every 3, 503)"
            ):
                f.activate()
        machine.run_task(
            max_tokens=12,
            max_total_tokens=4295,
            output_text="\x16øq",
            provider_fails=False,
        )
        machine.run_task(
            max_tokens=None,
            max_total_tokens=1620,
            output_text="0\x1bØg",
            provider_fails=False,
        )
        machine.run_with_fallback(output_text="^\x18ª")
        machine.run_with_fallback(
            output_text="1𛉪\x1f\U00096561Ñ\U00106080©\x9a'iâ\x03\U0007d3bfÆ\x8b\U000b459e"
        )
        for f in machine._faults:
            if (
                f.name
                == "intermittent_http_error(tests.test_chaos_engine._chaos_provider_generate, every 3, 503)"
            ):
                f.deactivate()
        for f in machine._faults:
            if (
                f.name
                == "intermittent_http_error(tests.test_chaos_engine._chaos_provider_generate, every 3, 503)"
            ):
                f.activate()
        machine.run_with_verification(
            output_text="\U000e23ef\x1d",
            substrings=["Tê³𥈳Å", "#\x8e\x1b@\x89\x8a\U00104436", "´"],
        )
        machine.run_with_verification(
            output_text="\x04?g𡸻",
            substrings=[
                "귴§ø",
                "¯\x97Úþ\U00049b10\U000593ad\U0006ba17ò",
                "Þ/\x8e5\x02Dcm\x11z",
            ],
        )
        machine.run_with_verification(
            output_text="W&çé阋*",
            substrings=[
                "_\t\x8dÈ\x83¹f\x91ðÑ",
                "\x12\x02\U0004ee5eW\x03É¸\U000d3c8b\x1d=",
                "\x9bÏ×[^þ\x13Ò\x8d\x9b",
            ],
        )
        machine.run_task(
            max_tokens=637,
            max_total_tokens=929,
            output_text="ÛA©\x83\x08I\U00044a64¦\U000bc97b",
            provider_fails=True,
        )
        machine.run_with_fallback(output_text="\rß\U000407f9aëi\U000a9166æ\\©")
        machine.run_with_verification(
            output_text="\x95",
            substrings=[
                "é¤\x08Ñ𣑶|\U000ce639E;\x8a",
                "sõ\U000625f7\U0007b09dG\U0006f8c3",
            ],
        )
        machine.run_task(
            max_tokens=954,
            max_total_tokens=2682,
            output_text="\x8d\U000ba6fe¬Z",
            provider_fails=False,
        )
        machine.run_task(
            max_tokens=1,
            max_total_tokens=1591,
            output_text="µYÇ¨\U00041a42I\U0008136bµjº\x8e\U00038562\U000fc95c2\U000ac68c¼Y\t+çþ",
            provider_fails=True,
        )
        for f in machine._faults:
            if (
                f.name
                == "intermittent_http_error(tests.test_chaos_engine._chaos_provider_generate, every 3, 503)"
            ):
                f.deactivate()
        machine.run_with_fallback(output_text='"Z')
    finally:
        machine.teardown()


def test_explore_providerfallbackchaos_6():
    """ProviderFallbackChaos: 41 steps, 221 edges"""
    machine = ProviderFallbackChaos()
    try:
        machine.empty_fallback_list()
        machine.empty_fallback_list()
        machine.fallback_chain(has_working=True, n_failing=0)
        machine.empty_fallback_list()
        machine.empty_fallback_list()
        machine.empty_fallback_list()
        machine.empty_fallback_list()
        machine.empty_fallback_list()
        machine.fallback_chain(has_working=False, n_failing=1)
        machine.empty_fallback_list()
        machine.empty_fallback_list()
        machine.empty_fallback_list()
        machine.empty_fallback_list()
        machine.empty_fallback_list()
        machine.empty_fallback_list()
        machine.empty_fallback_list()
        machine.fallback_chain(has_working=True, n_failing=2)
        machine.empty_fallback_list()
        machine.fallback_chain(has_working=False, n_failing=3)
        machine.fallback_chain(has_working=True, n_failing=4)
        machine.empty_fallback_list()
        machine.empty_fallback_list()
        machine.fallback_chain(has_working=False, n_failing=0)
        machine.fallback_chain(has_working=False, n_failing=1)
        machine.fallback_chain(has_working=True, n_failing=4)
        machine.empty_fallback_list()
        machine.empty_fallback_list()
        machine.fallback_chain(has_working=True, n_failing=3)
        machine.empty_fallback_list()
        machine.empty_fallback_list()
        machine.fallback_chain(has_working=False, n_failing=2)
        machine.empty_fallback_list()
        machine.fallback_chain(has_working=False, n_failing=2)
        machine.fallback_chain(has_working=True, n_failing=0)
        machine.fallback_chain(has_working=True, n_failing=4)
        machine.empty_fallback_list()
        machine.fallback_chain(has_working=False, n_failing=1)
        machine.empty_fallback_list()
        machine.fallback_chain(has_working=True, n_failing=3)
        machine.empty_fallback_list()
        machine.fallback_chain(has_working=False, n_failing=0)
    finally:
        machine.teardown()


def test_explore_circuitbreakerchaos_7():
    """CircuitBreakerChaos: 41 steps, 96 edges"""
    machine = CircuitBreakerChaos()
    try:
        for f in machine._faults:
            if f.name == "jitter(time.time, 0.001)":
                f.activate()
        for f in machine._faults:
            if f.name == "jitter(time.time, 0.001)":
                f.deactivate()
        machine.manual_reset()
        for f in machine._faults:
            if f.name == "jitter(time.time, 0.001)":
                f.activate()
        for f in machine._faults:
            if f.name == "jitter(time.time, 0.001)":
                f.deactivate()
        for f in machine._faults:
            if f.name == "jitter(time.time, 0.001)":
                f.activate()
        machine.manual_reset()
        machine.just_fail()
        machine.check_and_fail()
        machine.check_and_succeed()
        machine.concurrent_failures()
        for f in machine._faults:
            if f.name == "jitter(time.time, 0.001)":
                f.deactivate()
        machine.concurrent_failures()
        for f in machine._faults:
            if f.name == "jitter(time.time, 0.001)":
                f.activate()
        for f in machine._faults:
            if f.name == "jitter(time.time, 0.001)":
                f.deactivate()
        machine.check_and_fail()
        machine.manual_reset()
        for f in machine._faults:
            if f.name == "jitter(time.time, 0.001)":
                f.activate()
        for f in machine._faults:
            if f.name == "jitter(time.time, 0.001)":
                f.deactivate()
        machine.manual_reset()
        machine.concurrent_failures()
        machine.check_and_fail()
        for f in machine._faults:
            if f.name == "jitter(time.time, 0.001)":
                f.activate()
        machine.check_and_fail()
        machine.check_and_fail()
        machine.just_fail()
        machine.concurrent_failures()
        for f in machine._faults:
            if f.name == "jitter(time.time, 0.001)":
                f.deactivate()
        for f in machine._faults:
            if f.name == "jitter(time.time, 0.001)":
                f.activate()
        machine.check_and_fail()
        machine.check_and_succeed()
        machine.check_and_succeed()
        for f in machine._faults:
            if f.name == "jitter(time.time, 0.001)":
                f.deactivate()
        for f in machine._faults:
            if f.name == "jitter(time.time, 0.001)":
                f.activate()
        machine.check_and_fail()
        for f in machine._faults:
            if f.name == "jitter(time.time, 0.001)":
                f.deactivate()
        machine.just_fail()
        for f in machine._faults:
            if f.name == "jitter(time.time, 0.001)":
                f.activate()
        machine.manual_reset()
        machine.concurrent_failures()
        for f in machine._faults:
            if f.name == "jitter(time.time, 0.001)":
                f.deactivate()
    finally:
        machine.teardown()


def test_explore_concurrencylimiterchaos_8():
    """ConcurrencyLimiterChaos: 41 steps, 32 edges"""
    machine = ConcurrencyLimiterChaos()
    try:
        machine.acquire_blocking()
        machine.acquire_blocking()
        machine.concurrent_acquire_burst()
        machine.acquire_nonblocking()
        machine.acquire_blocking()
        machine.acquire_blocking()
        machine.acquire_blocking()
        machine.concurrent_acquire_burst()
        machine.acquire_blocking()
        machine.concurrent_acquire_burst()
        machine.concurrent_acquire_burst()
        machine.concurrent_acquire_burst()
        machine.acquire_blocking()
        machine.concurrent_acquire_burst()
        machine.acquire_nonblocking()
        machine.acquire_blocking()
        machine.acquire_blocking()
        machine.acquire_blocking()
        machine.acquire_blocking()
        machine.acquire_blocking()
        machine.concurrent_acquire_burst()
        machine.concurrent_acquire_burst()
        machine.acquire_blocking()
        machine.concurrent_acquire_burst()
        machine.acquire_blocking()
        machine.concurrent_acquire_burst()
        machine.concurrent_acquire_burst()
        machine.concurrent_acquire_burst()
        machine.concurrent_acquire_burst()
        machine.acquire_nonblocking()
        machine.acquire_blocking()
        machine.acquire_nonblocking()
        machine.concurrent_acquire_burst()
        machine.acquire_nonblocking()
        machine.acquire_blocking()
        machine.acquire_blocking()
        machine.concurrent_acquire_burst()
        machine.acquire_nonblocking()
        machine.acquire_nonblocking()
        machine.acquire_nonblocking()
        machine.acquire_blocking()
    finally:
        machine.teardown()


def test_explore_metricscollectorchaos_9():
    """MetricsCollectorChaos: 41 steps, 205 edges"""
    machine = MetricsCollectorChaos()
    try:
        machine.check_prometheus_format()
        machine.check_prometheus_format()
        machine.set_queue_depth(depth=241, node="node-0")
        machine.record_admission(accepted=False)
        machine.concurrent_snapshot()
        machine.concurrent_snapshot()
        machine.concurrent_snapshot()
        machine.set_queue_depth(depth=864, node="node-1")
        machine.check_prometheus_format()
        machine.set_queue_depth(depth=448, node="node-2")
        machine.set_queue_depth(depth=612, node="node-0")
        machine.set_circuit_state(node="node-2", state="open")
        machine.check_prometheus_format()
        machine.set_circuit_state(node="node-1", state="half_open")
        machine.record_request(duration=0.1, node="node-2", success=False)
        machine.check_prometheus_format()
        machine.check_prometheus_format()
        machine.check_prometheus_format()
        machine.concurrent_snapshot()
        machine.concurrent_snapshot()
        machine.set_circuit_state(node="node-0", state="closed")
        machine.set_circuit_state(node="node-0", state="closed")
        machine.check_prometheus_format()
        machine.set_circuit_state(node="node-1", state="half_open")
        machine.concurrent_snapshot()
        machine.set_queue_depth(depth=642, node="node-1")
        machine.set_queue_depth(depth=0, node="node-2")
        machine.set_queue_depth(depth=1000, node="node-2")
        machine.set_circuit_state(node="node-2", state="open")
        machine.record_request(duration=16471.17013768737, node="node-1", success=True)
        machine.concurrent_snapshot()
        machine.record_request(duration=29999.999999999996, node="node-0", success=True)
        machine.set_circuit_state(node="node-1", state="closed")
        machine.record_admission(accepted=False)
        machine.take_snapshot()
        machine.take_snapshot()
        machine.check_prometheus_format()
        machine.take_snapshot()
        machine.take_snapshot()
        machine.concurrent_snapshot()
        machine.set_queue_depth(depth=664, node="node-0")
    finally:
        machine.teardown()


def test_explore_sessionstatechaos_10():
    """SessionStateChaos: 41 steps, 58 edges"""
    machine = SessionStateChaos()
    try:
        machine.add_exchange(
            assistant_text="ëÊw",
            cost=0.0,
            tokens=29,
            user_text="\U0003b515Ç³\U0004c8aa",
        )
        machine.add_exchange(
            assistant_text="À¥Þfá\x18\U000f9fbf\x90",
            cost=0.057680005306441254,
            tokens=19,
            user_text="\x91 ²~D",
        )
        machine.try_raise_cost_cap(new_cap=61.951744788631586)
        machine.clear_history()
        machine.check_budget_cap()
        machine.check_budget_cap()
        machine.check_budget_cap()
        machine.try_raise_cost_cap(new_cap=0.01)
        machine.add_exchange(
            assistant_text="\x8e\U000b908c\x06ð\x10V",
            cost=0.005091478158476771,
            tokens=20,
            user_text="©",
        )
        machine.try_raise_cost_cap(new_cap=30.0)
        machine.try_raise_cost_cap(new_cap=34.05476513647414)
        machine.serialize_roundtrip()
        machine.add_exchange(
            assistant_text="¾\x19W¼\x96Êc\x0b\U00054610\x03\U00083852\U000e880a\x8bÃ",
            cost=0.25,
            tokens=0,
            user_text="ê.§¾²e?*",
        )
        machine.serialize_roundtrip()
        machine.format_history()
        machine.add_exchange(
            assistant_text="\x8f\x88\x8c", cost=1e-12, tokens=14, user_text="/𤄫e"
        )
        machine.add_exchange(
            assistant_text="\U0004c8ecV®",
            cost=0.22496228666222412,
            tokens=13,
            user_text="\xa0\x12ø\x10t",
        )
        machine.add_exchange(
            assistant_text="0",
            cost=0.28088790679751513,
            tokens=37,
            user_text="B÷·ÆZ\r\x8e13",
        )
        machine.check_budget_cap()
        machine.check_budget_cap()
        machine.serialize_roundtrip()
        machine.serialize_roundtrip()
        machine.add_exchange(
            assistant_text="H\x94",
            cost=0.0005,
            tokens=7,
            user_text="¦\U000eafbb´L\U000716fe\x08\x13",
        )
        machine.serialize_roundtrip()
        machine.check_budget_cap()
        machine.try_raise_cost_cap(new_cap=0.010000000000000002)
        machine.try_raise_cost_cap(new_cap=85.17848265275624)
        machine.try_raise_cost_cap(new_cap=41.8372441550479)
        machine.serialize_roundtrip()
        machine.format_history()
        machine.check_budget_cap()
        machine.format_history()
        machine.serialize_roundtrip()
        machine.clear_history()
        machine.try_raise_token_cap(new_cap=4719)
        machine.try_raise_token_cap(new_cap=195)
        machine.add_exchange(
            assistant_text="Ü(ÿÓ\x04",
            cost=1.1125369292536007e-308,
            tokens=21,
            user_text="\x87\U000b9a6eÂ\U000b5ebaD",
        )
        machine.try_raise_token_cap(new_cap=6817)
        machine.try_raise_token_cap(new_cap=5041)
        machine.check_budget_cap()
        machine.try_raise_cost_cap(new_cap=66.64862476738793)
    finally:
        machine.teardown()
